package org.alc.ws.stub.fedex.track;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-10-22T17:30:47.151+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "TrackService", 
                  wsdlLocation = "file:/C:/Users/I311384.GLOBAL/Desktop/SW/cygwin/home/I311384/gitProj/J2EE/sae/webapps/alcapphello/design/wsdl/FedexTrackService_v9.wsdl",
                  targetNamespace = "http://fedex.com/ws/track/v9") 
public class TrackService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fedex.com/ws/track/v9", "TrackService");
    public final static QName TrackServicePort = new QName("http://fedex.com/ws/track/v9", "TrackServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/I311384.GLOBAL/Desktop/SW/cygwin/home/I311384/gitProj/J2EE/sae/webapps/alcapphello/design/wsdl/FedexTrackService_v9.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TrackService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/I311384.GLOBAL/Desktop/SW/cygwin/home/I311384/gitProj/J2EE/sae/webapps/alcapphello/design/wsdl/FedexTrackService_v9.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TrackService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TrackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrackService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TrackService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TrackService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TrackService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TrackPortType
     */
    @WebEndpoint(name = "TrackServicePort")
    public TrackPortType getTrackServicePort() {
        return super.getPort(TrackServicePort, TrackPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrackPortType
     */
    @WebEndpoint(name = "TrackServicePort")
    public TrackPortType getTrackServicePort(WebServiceFeature... features) {
        return super.getPort(TrackServicePort, TrackPortType.class, features);
    }

}
