
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.alc.ws.stub.fedex.track;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-10-22T17:30:47.133+08:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "TrackService",
                      portName = "TrackServicePort",
                      targetNamespace = "http://fedex.com/ws/track/v9",
                      wsdlLocation = "file:/C:/Users/I311384.GLOBAL/Desktop/SW/cygwin/home/I311384/gitProj/J2EE/sae/webapps/alcapphello/design/wsdl/FedexTrackService_v9.wsdl",
                      endpointInterface = "org.alc.ws.stub.fedex.TrackPortType")
                      
public class TrackPortTypeImpl implements TrackPortType {

    private static final Logger LOG = Logger.getLogger(TrackPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.alc.ws.stub.fedex.TrackPortType#retrieveSignatureProofOfDeliveryLetter(org.alc.ws.stub.fedex.SignatureProofOfDeliveryLetterRequest  signatureProofOfDeliveryLetterRequest )*
     */
    public org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryLetterReply retrieveSignatureProofOfDeliveryLetter(SignatureProofOfDeliveryLetterRequest signatureProofOfDeliveryLetterRequest) { 
        LOG.info("Executing operation retrieveSignatureProofOfDeliveryLetter");
        System.out.println(signatureProofOfDeliveryLetterRequest);
        try {
            org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryLetterReply _return = new org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryLetterReply();
            org.alc.ws.stub.fedex.track.NotificationSeverityType _returnHighestSeverity = org.alc.ws.stub.fedex.track.NotificationSeverityType.FAILURE;
            _return.setHighestSeverity(_returnHighestSeverity);
            java.util.List<org.alc.ws.stub.fedex.track.Notification> _returnNotifications = new java.util.ArrayList<org.alc.ws.stub.fedex.track.Notification>();
            org.alc.ws.stub.fedex.track.Notification _returnNotificationsVal1 = new org.alc.ws.stub.fedex.track.Notification();
            org.alc.ws.stub.fedex.track.NotificationSeverityType _returnNotificationsVal1Severity = org.alc.ws.stub.fedex.track.NotificationSeverityType.SUCCESS;
            _returnNotificationsVal1.setSeverity(_returnNotificationsVal1Severity);
            _returnNotificationsVal1.setSource("Source-780312324");
            _returnNotificationsVal1.setCode("Code545800993");
            _returnNotificationsVal1.setMessage("Message610834009");
            _returnNotificationsVal1.setLocalizedMessage("LocalizedMessage1356919516");
            java.util.List<org.alc.ws.stub.fedex.track.NotificationParameter> _returnNotificationsVal1MessageParameters = new java.util.ArrayList<org.alc.ws.stub.fedex.track.NotificationParameter>();
            _returnNotificationsVal1.getMessageParameters().addAll(_returnNotificationsVal1MessageParameters);
            _returnNotifications.add(_returnNotificationsVal1);
            _return.getNotifications().addAll(_returnNotifications);
            org.alc.ws.stub.fedex.track.TransactionDetail _returnTransactionDetail = new org.alc.ws.stub.fedex.track.TransactionDetail();
            _returnTransactionDetail.setCustomerTransactionId("CustomerTransactionId-279519635");
            org.alc.ws.stub.fedex.track.Localization _returnTransactionDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
            _returnTransactionDetailLocalization.setLanguageCode("LanguageCode474175442");
            _returnTransactionDetailLocalization.setLocaleCode("LocaleCode-16510504");
            _returnTransactionDetail.setLocalization(_returnTransactionDetailLocalization);
            _return.setTransactionDetail(_returnTransactionDetail);
            org.alc.ws.stub.fedex.track.VersionId _returnVersion = new org.alc.ws.stub.fedex.track.VersionId();
            _returnVersion.setServiceId("ServiceId142362252");
            _returnVersion.setMajor(-1679036916);
            _returnVersion.setIntermediate(-1924378870);
            _returnVersion.setMinor(897502321);
            _return.setVersion(_returnVersion);
            byte[] _returnLetter = new byte[] {};
            _return.setLetter(_returnLetter);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.alc.ws.stub.fedex.TrackPortType#sendNotifications(org.alc.ws.stub.fedex.SendNotificationsRequest  sendNotificationsRequest )*
     */
    public org.alc.ws.stub.fedex.track.SendNotificationsReply sendNotifications(SendNotificationsRequest sendNotificationsRequest) { 
        LOG.info("Executing operation sendNotifications");
        System.out.println(sendNotificationsRequest);
        try {
            org.alc.ws.stub.fedex.track.SendNotificationsReply _return = new org.alc.ws.stub.fedex.track.SendNotificationsReply();
            org.alc.ws.stub.fedex.track.NotificationSeverityType _returnHighestSeverity = org.alc.ws.stub.fedex.track.NotificationSeverityType.ERROR;
            _return.setHighestSeverity(_returnHighestSeverity);
            java.util.List<org.alc.ws.stub.fedex.track.Notification> _returnNotifications = new java.util.ArrayList<org.alc.ws.stub.fedex.track.Notification>();
            org.alc.ws.stub.fedex.track.Notification _returnNotificationsVal1 = new org.alc.ws.stub.fedex.track.Notification();
            org.alc.ws.stub.fedex.track.NotificationSeverityType _returnNotificationsVal1Severity = org.alc.ws.stub.fedex.track.NotificationSeverityType.NOTE;
            _returnNotificationsVal1.setSeverity(_returnNotificationsVal1Severity);
            _returnNotificationsVal1.setSource("Source1020796301");
            _returnNotificationsVal1.setCode("Code1136496534");
            _returnNotificationsVal1.setMessage("Message-474659274");
            _returnNotificationsVal1.setLocalizedMessage("LocalizedMessage1616898730");
            java.util.List<org.alc.ws.stub.fedex.track.NotificationParameter> _returnNotificationsVal1MessageParameters = new java.util.ArrayList<org.alc.ws.stub.fedex.track.NotificationParameter>();
            _returnNotificationsVal1.getMessageParameters().addAll(_returnNotificationsVal1MessageParameters);
            _returnNotifications.add(_returnNotificationsVal1);
            _return.getNotifications().addAll(_returnNotifications);
            org.alc.ws.stub.fedex.track.TransactionDetail _returnTransactionDetail = new org.alc.ws.stub.fedex.track.TransactionDetail();
            _returnTransactionDetail.setCustomerTransactionId("CustomerTransactionId738286102");
            org.alc.ws.stub.fedex.track.Localization _returnTransactionDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
            _returnTransactionDetailLocalization.setLanguageCode("LanguageCode-1706351380");
            _returnTransactionDetailLocalization.setLocaleCode("LocaleCode1173432168");
            _returnTransactionDetail.setLocalization(_returnTransactionDetailLocalization);
            _return.setTransactionDetail(_returnTransactionDetail);
            org.alc.ws.stub.fedex.track.VersionId _returnVersion = new org.alc.ws.stub.fedex.track.VersionId();
            _returnVersion.setServiceId("ServiceId-219144672");
            _returnVersion.setMajor(1168669854);
            _returnVersion.setIntermediate(509238849);
            _returnVersion.setMinor(-1342838250);
            _return.setVersion(_returnVersion);
            _return.setDuplicateWaybill(Boolean.valueOf(false));
            _return.setMoreDataAvailable(Boolean.valueOf(true));
            _return.setPagingToken("PagingToken885795005");
            java.util.List<org.alc.ws.stub.fedex.track.TrackNotificationPackage> _returnPackages = new java.util.ArrayList<org.alc.ws.stub.fedex.track.TrackNotificationPackage>();
            org.alc.ws.stub.fedex.track.TrackNotificationPackage _returnPackagesVal1 = new org.alc.ws.stub.fedex.track.TrackNotificationPackage();
            _returnPackagesVal1.setTrackingNumber("TrackingNumber-1396533481");
            _returnPackagesVal1.setTrackingNumberUniqueIdentifiers("TrackingNumberUniqueIdentifiers1590075560");
            org.alc.ws.stub.fedex.track.CarrierCodeType _returnPackagesVal1CarrierCode = org.alc.ws.stub.fedex.track.CarrierCodeType.FXFR;
            _returnPackagesVal1.setCarrierCode(_returnPackagesVal1CarrierCode);
            _returnPackagesVal1.setShipDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-22T17:30:47.142+08:00"));
            org.alc.ws.stub.fedex.track.Address _returnPackagesVal1Destination = new org.alc.ws.stub.fedex.track.Address();
            java.util.List<java.lang.String> _returnPackagesVal1DestinationStreetLines = new java.util.ArrayList<java.lang.String>();
            _returnPackagesVal1Destination.getStreetLines().addAll(_returnPackagesVal1DestinationStreetLines);
            _returnPackagesVal1Destination.setCity("City933699414");
            _returnPackagesVal1Destination.setStateOrProvinceCode("StateOrProvinceCode924347391");
            _returnPackagesVal1Destination.setPostalCode("PostalCode-564919994");
            _returnPackagesVal1Destination.setUrbanizationCode("UrbanizationCode52363773");
            _returnPackagesVal1Destination.setCountryCode("CountryCode-1169076087");
            _returnPackagesVal1Destination.setCountryName("CountryName128172229");
            _returnPackagesVal1Destination.setResidential(Boolean.valueOf(false));
            _returnPackagesVal1.setDestination(_returnPackagesVal1Destination);
            java.util.List<org.alc.ws.stub.fedex.track.TrackNotificationRecipientDetail> _returnPackagesVal1RecipientDetails = new java.util.ArrayList<org.alc.ws.stub.fedex.track.TrackNotificationRecipientDetail>();
            _returnPackagesVal1.getRecipientDetails().addAll(_returnPackagesVal1RecipientDetails);
            _returnPackages.add(_returnPackagesVal1);
            _return.getPackages().addAll(_returnPackages);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.alc.ws.stub.fedex.TrackPortType#sendSignatureProofOfDeliveryFax(org.alc.ws.stub.fedex.SignatureProofOfDeliveryFaxRequest  signatureProofOfDeliveryFaxRequest )*
     */
    public org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryFaxReply sendSignatureProofOfDeliveryFax(SignatureProofOfDeliveryFaxRequest signatureProofOfDeliveryFaxRequest) { 
        LOG.info("Executing operation sendSignatureProofOfDeliveryFax");
        System.out.println(signatureProofOfDeliveryFaxRequest);
        try {
            org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryFaxReply _return = new org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryFaxReply();
            org.alc.ws.stub.fedex.track.NotificationSeverityType _returnHighestSeverity = org.alc.ws.stub.fedex.track.NotificationSeverityType.WARNING;
            _return.setHighestSeverity(_returnHighestSeverity);
            java.util.List<org.alc.ws.stub.fedex.track.Notification> _returnNotifications = new java.util.ArrayList<org.alc.ws.stub.fedex.track.Notification>();
            org.alc.ws.stub.fedex.track.Notification _returnNotificationsVal1 = new org.alc.ws.stub.fedex.track.Notification();
            org.alc.ws.stub.fedex.track.NotificationSeverityType _returnNotificationsVal1Severity = org.alc.ws.stub.fedex.track.NotificationSeverityType.WARNING;
            _returnNotificationsVal1.setSeverity(_returnNotificationsVal1Severity);
            _returnNotificationsVal1.setSource("Source-1491393628");
            _returnNotificationsVal1.setCode("Code-953032172");
            _returnNotificationsVal1.setMessage("Message-408782698");
            _returnNotificationsVal1.setLocalizedMessage("LocalizedMessage-746731733");
            java.util.List<org.alc.ws.stub.fedex.track.NotificationParameter> _returnNotificationsVal1MessageParameters = new java.util.ArrayList<org.alc.ws.stub.fedex.track.NotificationParameter>();
            _returnNotificationsVal1.getMessageParameters().addAll(_returnNotificationsVal1MessageParameters);
            _returnNotifications.add(_returnNotificationsVal1);
            _return.getNotifications().addAll(_returnNotifications);
            org.alc.ws.stub.fedex.track.TransactionDetail _returnTransactionDetail = new org.alc.ws.stub.fedex.track.TransactionDetail();
            _returnTransactionDetail.setCustomerTransactionId("CustomerTransactionId-187052219");
            org.alc.ws.stub.fedex.track.Localization _returnTransactionDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
            _returnTransactionDetailLocalization.setLanguageCode("LanguageCode-1816581493");
            _returnTransactionDetailLocalization.setLocaleCode("LocaleCode795706906");
            _returnTransactionDetail.setLocalization(_returnTransactionDetailLocalization);
            _return.setTransactionDetail(_returnTransactionDetail);
            org.alc.ws.stub.fedex.track.VersionId _returnVersion = new org.alc.ws.stub.fedex.track.VersionId();
            _returnVersion.setServiceId("ServiceId-1892549643");
            _returnVersion.setMajor(1932058397);
            _returnVersion.setIntermediate(374656269);
            _returnVersion.setMinor(-1221317938);
            _return.setVersion(_returnVersion);
            _return.setFaxConfirmationNumber("FaxConfirmationNumber-1880032205");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.alc.ws.stub.fedex.TrackPortType#track(org.alc.ws.stub.fedex.TrackRequest  trackRequest )*
     */
    public org.alc.ws.stub.fedex.track.TrackReply track(TrackRequest trackRequest) { 
        LOG.info("Executing operation track");
        System.out.println(trackRequest);
        try {
            org.alc.ws.stub.fedex.track.TrackReply _return = new org.alc.ws.stub.fedex.track.TrackReply();
            org.alc.ws.stub.fedex.track.NotificationSeverityType _returnHighestSeverity = org.alc.ws.stub.fedex.track.NotificationSeverityType.WARNING;
            _return.setHighestSeverity(_returnHighestSeverity);
            java.util.List<org.alc.ws.stub.fedex.track.Notification> _returnNotifications = new java.util.ArrayList<org.alc.ws.stub.fedex.track.Notification>();
            org.alc.ws.stub.fedex.track.Notification _returnNotificationsVal1 = new org.alc.ws.stub.fedex.track.Notification();
            org.alc.ws.stub.fedex.track.NotificationSeverityType _returnNotificationsVal1Severity = org.alc.ws.stub.fedex.track.NotificationSeverityType.NOTE;
            _returnNotificationsVal1.setSeverity(_returnNotificationsVal1Severity);
            _returnNotificationsVal1.setSource("Source-235850724");
            _returnNotificationsVal1.setCode("Code-134191301");
            _returnNotificationsVal1.setMessage("Message-819737753");
            _returnNotificationsVal1.setLocalizedMessage("LocalizedMessage-744362421");
            java.util.List<org.alc.ws.stub.fedex.track.NotificationParameter> _returnNotificationsVal1MessageParameters = new java.util.ArrayList<org.alc.ws.stub.fedex.track.NotificationParameter>();
            _returnNotificationsVal1.getMessageParameters().addAll(_returnNotificationsVal1MessageParameters);
            _returnNotifications.add(_returnNotificationsVal1);
            _return.getNotifications().addAll(_returnNotifications);
            org.alc.ws.stub.fedex.track.TransactionDetail _returnTransactionDetail = new org.alc.ws.stub.fedex.track.TransactionDetail();
            _returnTransactionDetail.setCustomerTransactionId("CustomerTransactionId-1268357809");
            org.alc.ws.stub.fedex.track.Localization _returnTransactionDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
            _returnTransactionDetailLocalization.setLanguageCode("LanguageCode-1367407006");
            _returnTransactionDetailLocalization.setLocaleCode("LocaleCode-684125746");
            _returnTransactionDetail.setLocalization(_returnTransactionDetailLocalization);
            _return.setTransactionDetail(_returnTransactionDetail);
            org.alc.ws.stub.fedex.track.VersionId _returnVersion = new org.alc.ws.stub.fedex.track.VersionId();
            _returnVersion.setServiceId("ServiceId69727738");
            _returnVersion.setMajor(1729432916);
            _returnVersion.setIntermediate(91924838);
            _returnVersion.setMinor(-42668832);
            _return.setVersion(_returnVersion);
            java.util.List<org.alc.ws.stub.fedex.track.CompletedTrackDetail> _returnCompletedTrackDetails = new java.util.ArrayList<org.alc.ws.stub.fedex.track.CompletedTrackDetail>();
            org.alc.ws.stub.fedex.track.CompletedTrackDetail _returnCompletedTrackDetailsVal1 = new org.alc.ws.stub.fedex.track.CompletedTrackDetail();
            org.alc.ws.stub.fedex.track.NotificationSeverityType _returnCompletedTrackDetailsVal1HighestSeverity = org.alc.ws.stub.fedex.track.NotificationSeverityType.ERROR;
            _returnCompletedTrackDetailsVal1.setHighestSeverity(_returnCompletedTrackDetailsVal1HighestSeverity);
            java.util.List<org.alc.ws.stub.fedex.track.Notification> _returnCompletedTrackDetailsVal1Notifications = new java.util.ArrayList<org.alc.ws.stub.fedex.track.Notification>();
            _returnCompletedTrackDetailsVal1.getNotifications().addAll(_returnCompletedTrackDetailsVal1Notifications);
            _returnCompletedTrackDetailsVal1.setDuplicateWaybill(Boolean.valueOf(false));
            _returnCompletedTrackDetailsVal1.setMoreData(Boolean.valueOf(true));
            _returnCompletedTrackDetailsVal1.setPagingToken("PagingToken-1404254026");
            _returnCompletedTrackDetailsVal1.setTrackDetailsCount(new java.math.BigInteger("-46447893825075179197040745011740006449"));
            java.util.List<org.alc.ws.stub.fedex.track.TrackDetail> _returnCompletedTrackDetailsVal1TrackDetails = new java.util.ArrayList<org.alc.ws.stub.fedex.track.TrackDetail>();
            _returnCompletedTrackDetailsVal1.getTrackDetails().addAll(_returnCompletedTrackDetailsVal1TrackDetails);
            _returnCompletedTrackDetails.add(_returnCompletedTrackDetailsVal1);
            _return.getCompletedTrackDetails().addAll(_returnCompletedTrackDetails);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
