package org.alc.ws.stub.fedex.track;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-10-22T17:30:47.145+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://fedex.com/ws/track/v9", name = "TrackPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TrackPortType {

    @WebResult(name = "SignatureProofOfDeliveryLetterReply", targetNamespace = "http://fedex.com/ws/track/v9", partName = "SignatureProofOfDeliveryLetterReply")
    @WebMethod(action = "http://fedex.com/ws/track/v9/retrieveSignatureProofOfDeliveryLetter")
    public SignatureProofOfDeliveryLetterReply retrieveSignatureProofOfDeliveryLetter(
        @WebParam(partName = "SignatureProofOfDeliveryLetterRequest", name = "SignatureProofOfDeliveryLetterRequest", targetNamespace = "http://fedex.com/ws/track/v9")
        SignatureProofOfDeliveryLetterRequest signatureProofOfDeliveryLetterRequest
    );

    @WebResult(name = "SendNotificationsReply", targetNamespace = "http://fedex.com/ws/track/v9", partName = "SendNotificationsReply")
    @WebMethod(action = "http://fedex.com/ws/track/v9/sendNotifications")
    public SendNotificationsReply sendNotifications(
        @WebParam(partName = "SendNotificationsRequest", name = "SendNotificationsRequest", targetNamespace = "http://fedex.com/ws/track/v9")
        SendNotificationsRequest sendNotificationsRequest
    );

    @WebResult(name = "SignatureProofOfDeliveryFaxReply", targetNamespace = "http://fedex.com/ws/track/v9", partName = "SignatureProofOfDeliveryFaxReply")
    @WebMethod(action = "http://fedex.com/ws/track/v9/sendSignatureProofOfDeliveryFax")
    public SignatureProofOfDeliveryFaxReply sendSignatureProofOfDeliveryFax(
        @WebParam(partName = "SignatureProofOfDeliveryFaxRequest", name = "SignatureProofOfDeliveryFaxRequest", targetNamespace = "http://fedex.com/ws/track/v9")
        SignatureProofOfDeliveryFaxRequest signatureProofOfDeliveryFaxRequest
    );

    @WebResult(name = "TrackReply", targetNamespace = "http://fedex.com/ws/track/v9", partName = "TrackReply")
    @WebMethod(action = "http://fedex.com/ws/track/v9/track")
    public TrackReply track(
        @WebParam(partName = "TrackRequest", name = "TrackRequest", targetNamespace = "http://fedex.com/ws/track/v9")
        TrackRequest trackRequest
    );
}
