
package org.alc.ws.stub.fedex.track;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-10-22T17:30:47.085+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class TrackPortType_TrackServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://fedex.com/ws/track/v9", "TrackService");

    private TrackPortType_TrackServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TrackService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TrackService ss = new TrackService(wsdlURL, SERVICE_NAME);
        TrackPortType port = ss.getTrackServicePort();  
        
        {
        System.out.println("Invoking retrieveSignatureProofOfDeliveryLetter...");
        org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryLetterRequest _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest = new org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryLetterRequest();
        org.alc.ws.stub.fedex.track.WebAuthenticationDetail _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestWebAuthenticationDetail = new org.alc.ws.stub.fedex.track.WebAuthenticationDetail();
        org.alc.ws.stub.fedex.track.WebAuthenticationCredential _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestWebAuthenticationDetailUserCredential = new org.alc.ws.stub.fedex.track.WebAuthenticationCredential();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestWebAuthenticationDetailUserCredential.setKey("Key1659948559");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestWebAuthenticationDetailUserCredential.setPassword("Password1212560936");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestWebAuthenticationDetail.setUserCredential(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestWebAuthenticationDetailUserCredential);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest.setWebAuthenticationDetail(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestWebAuthenticationDetail);
        org.alc.ws.stub.fedex.track.ClientDetail _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetail = new org.alc.ws.stub.fedex.track.ClientDetail();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetail.setAccountNumber("AccountNumber966672297");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetail.setMeterNumber("MeterNumber155507488");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetail.setIntegratorId("IntegratorId-128830345");
        org.alc.ws.stub.fedex.track.Localization _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetailLocalization.setLanguageCode("LanguageCode1750974373");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetailLocalization.setLocaleCode("LocaleCode1401735940");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetail.setLocalization(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetailLocalization);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest.setClientDetail(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestClientDetail);
        org.alc.ws.stub.fedex.track.TransactionDetail _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestTransactionDetail = new org.alc.ws.stub.fedex.track.TransactionDetail();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestTransactionDetail.setCustomerTransactionId("CustomerTransactionId-1138716378");
        org.alc.ws.stub.fedex.track.Localization _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestTransactionDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestTransactionDetailLocalization.setLanguageCode("LanguageCode-1398249987");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestTransactionDetailLocalization.setLocaleCode("LocaleCode1014851772");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestTransactionDetail.setLocalization(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestTransactionDetailLocalization);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest.setTransactionDetail(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestTransactionDetail);
        org.alc.ws.stub.fedex.track.VersionId _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestVersion = new org.alc.ws.stub.fedex.track.VersionId();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestVersion.setServiceId("ServiceId-2061751742");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestVersion.setMajor(1397011670);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestVersion.setIntermediate(-1121292597);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestVersion.setMinor(-1349853460);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest.setVersion(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestVersion);
        org.alc.ws.stub.fedex.track.QualifiedTrackingNumber _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumber = new org.alc.ws.stub.fedex.track.QualifiedTrackingNumber();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumber.setTrackingNumber("TrackingNumber463963463");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumber.setShipDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-22T17:30:47.119+08:00"));
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumber.setAccountNumber("AccountNumber-1867780635");
        org.alc.ws.stub.fedex.track.CarrierCodeType _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberCarrier = org.alc.ws.stub.fedex.track.CarrierCodeType.FXSP;
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumber.setCarrier(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberCarrier);
        org.alc.ws.stub.fedex.track.Address _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination = new org.alc.ws.stub.fedex.track.Address();
        java.util.List<java.lang.String> _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestinationStreetLines = new java.util.ArrayList<java.lang.String>();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination.getStreetLines().addAll(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestinationStreetLines);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination.setCity("City1873643358");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination.setStateOrProvinceCode("StateOrProvinceCode-401717623");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination.setPostalCode("PostalCode-1108749067");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination.setUrbanizationCode("UrbanizationCode1083325616");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination.setCountryCode("CountryCode-2090284999");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination.setCountryName("CountryName-902378542");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination.setResidential(Boolean.valueOf(false));
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumber.setDestination(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumberDestination);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest.setQualifiedTrackingNumber(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestQualifiedTrackingNumber);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest.setAdditionalComments("AdditionalComments-2067489653");
        org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryImageType _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestLetterFormat = org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryImageType.PNG;
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest.setLetterFormat(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestLetterFormat);
        org.alc.ws.stub.fedex.track.ContactAndAddress _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsignee = new org.alc.ws.stub.fedex.track.ContactAndAddress();
        org.alc.ws.stub.fedex.track.Contact _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact = new org.alc.ws.stub.fedex.track.Contact();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact.setPersonName("PersonName-234561724");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact.setTitle("Title-1941263319");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact.setCompanyName("CompanyName-1408238528");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact.setPhoneNumber("PhoneNumber1385071982");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact.setPhoneExtension("PhoneExtension1330658461");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact.setTollFreePhoneNumber("TollFreePhoneNumber2076147068");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact.setPagerNumber("PagerNumber846154624");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact.setFaxNumber("FaxNumber-1611059078");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact.setEMailAddress("EMailAddress6792892");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsignee.setContact(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeContact);
        org.alc.ws.stub.fedex.track.Address _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress = new org.alc.ws.stub.fedex.track.Address();
        java.util.List<java.lang.String> _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddressStreetLines = new java.util.ArrayList<java.lang.String>();
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress.getStreetLines().addAll(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddressStreetLines);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress.setCity("City317019734");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress.setStateOrProvinceCode("StateOrProvinceCode-1576097608");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress.setPostalCode("PostalCode2135449789");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress.setUrbanizationCode("UrbanizationCode1550930276");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress.setCountryCode("CountryCode822471866");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress.setCountryName("CountryName309881459");
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress.setResidential(Boolean.valueOf(true));
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsignee.setAddress(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsigneeAddress);
        _retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest.setConsignee(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequestConsignee);
        org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryLetterReply _retrieveSignatureProofOfDeliveryLetter__return = port.retrieveSignatureProofOfDeliveryLetter(_retrieveSignatureProofOfDeliveryLetter_signatureProofOfDeliveryLetterRequest);
        System.out.println("retrieveSignatureProofOfDeliveryLetter.result=" + _retrieveSignatureProofOfDeliveryLetter__return);


        }
        {
        System.out.println("Invoking sendNotifications...");
        org.alc.ws.stub.fedex.track.SendNotificationsRequest _sendNotifications_sendNotificationsRequest = new org.alc.ws.stub.fedex.track.SendNotificationsRequest();
        org.alc.ws.stub.fedex.track.WebAuthenticationDetail _sendNotifications_sendNotificationsRequestWebAuthenticationDetail = new org.alc.ws.stub.fedex.track.WebAuthenticationDetail();
        org.alc.ws.stub.fedex.track.WebAuthenticationCredential _sendNotifications_sendNotificationsRequestWebAuthenticationDetailUserCredential = new org.alc.ws.stub.fedex.track.WebAuthenticationCredential();
        _sendNotifications_sendNotificationsRequestWebAuthenticationDetailUserCredential.setKey("Key-1262378177");
        _sendNotifications_sendNotificationsRequestWebAuthenticationDetailUserCredential.setPassword("Password1382960402");
        _sendNotifications_sendNotificationsRequestWebAuthenticationDetail.setUserCredential(_sendNotifications_sendNotificationsRequestWebAuthenticationDetailUserCredential);
        _sendNotifications_sendNotificationsRequest.setWebAuthenticationDetail(_sendNotifications_sendNotificationsRequestWebAuthenticationDetail);
        org.alc.ws.stub.fedex.track.ClientDetail _sendNotifications_sendNotificationsRequestClientDetail = new org.alc.ws.stub.fedex.track.ClientDetail();
        _sendNotifications_sendNotificationsRequestClientDetail.setAccountNumber("AccountNumber1782504188");
        _sendNotifications_sendNotificationsRequestClientDetail.setMeterNumber("MeterNumber-514319570");
        _sendNotifications_sendNotificationsRequestClientDetail.setIntegratorId("IntegratorId-1840409564");
        org.alc.ws.stub.fedex.track.Localization _sendNotifications_sendNotificationsRequestClientDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
        _sendNotifications_sendNotificationsRequestClientDetailLocalization.setLanguageCode("LanguageCode1501697309");
        _sendNotifications_sendNotificationsRequestClientDetailLocalization.setLocaleCode("LocaleCode873695814");
        _sendNotifications_sendNotificationsRequestClientDetail.setLocalization(_sendNotifications_sendNotificationsRequestClientDetailLocalization);
        _sendNotifications_sendNotificationsRequest.setClientDetail(_sendNotifications_sendNotificationsRequestClientDetail);
        org.alc.ws.stub.fedex.track.TransactionDetail _sendNotifications_sendNotificationsRequestTransactionDetail = new org.alc.ws.stub.fedex.track.TransactionDetail();
        _sendNotifications_sendNotificationsRequestTransactionDetail.setCustomerTransactionId("CustomerTransactionId-2037184871");
        org.alc.ws.stub.fedex.track.Localization _sendNotifications_sendNotificationsRequestTransactionDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
        _sendNotifications_sendNotificationsRequestTransactionDetailLocalization.setLanguageCode("LanguageCode183380892");
        _sendNotifications_sendNotificationsRequestTransactionDetailLocalization.setLocaleCode("LocaleCode-1714230745");
        _sendNotifications_sendNotificationsRequestTransactionDetail.setLocalization(_sendNotifications_sendNotificationsRequestTransactionDetailLocalization);
        _sendNotifications_sendNotificationsRequest.setTransactionDetail(_sendNotifications_sendNotificationsRequestTransactionDetail);
        org.alc.ws.stub.fedex.track.VersionId _sendNotifications_sendNotificationsRequestVersion = new org.alc.ws.stub.fedex.track.VersionId();
        _sendNotifications_sendNotificationsRequestVersion.setServiceId("ServiceId2078759440");
        _sendNotifications_sendNotificationsRequestVersion.setMajor(1108701980);
        _sendNotifications_sendNotificationsRequestVersion.setIntermediate(-1853955166);
        _sendNotifications_sendNotificationsRequestVersion.setMinor(-964911493);
        _sendNotifications_sendNotificationsRequest.setVersion(_sendNotifications_sendNotificationsRequestVersion);
        _sendNotifications_sendNotificationsRequest.setTrackingNumber("TrackingNumber884779076");
        _sendNotifications_sendNotificationsRequest.setMultiPiece(Boolean.valueOf(false));
        _sendNotifications_sendNotificationsRequest.setPagingToken("PagingToken607712170");
        _sendNotifications_sendNotificationsRequest.setTrackingNumberUniqueId("TrackingNumberUniqueId1410972182");
        _sendNotifications_sendNotificationsRequest.setShipDateRangeBegin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-22T17:30:47.125+08:00"));
        _sendNotifications_sendNotificationsRequest.setShipDateRangeEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-22T17:30:47.126+08:00"));
        _sendNotifications_sendNotificationsRequest.setSenderEMailAddress("SenderEMailAddress-1098433632");
        _sendNotifications_sendNotificationsRequest.setSenderContactName("SenderContactName-2136409416");
        org.alc.ws.stub.fedex.track.EMailNotificationDetail _sendNotifications_sendNotificationsRequestNotificationDetail = new org.alc.ws.stub.fedex.track.EMailNotificationDetail();
        _sendNotifications_sendNotificationsRequestNotificationDetail.setPersonalMessage("PersonalMessage38389732");
        java.util.List<org.alc.ws.stub.fedex.track.EMailNotificationRecipient> _sendNotifications_sendNotificationsRequestNotificationDetailRecipients = new java.util.ArrayList<org.alc.ws.stub.fedex.track.EMailNotificationRecipient>();
        org.alc.ws.stub.fedex.track.EMailNotificationRecipient _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1 = new org.alc.ws.stub.fedex.track.EMailNotificationRecipient();
        org.alc.ws.stub.fedex.track.EMailNotificationRecipientType _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1EMailNotificationRecipientType = org.alc.ws.stub.fedex.track.EMailNotificationRecipientType.SHIPPER;
        _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1.setEMailNotificationRecipientType(_sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1EMailNotificationRecipientType);
        _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1.setEMailAddress("EMailAddress-888416617");
        java.util.List<org.alc.ws.stub.fedex.track.EMailNotificationEventType> _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1NotificationEventsRequested = new java.util.ArrayList<org.alc.ws.stub.fedex.track.EMailNotificationEventType>();
        _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1.getNotificationEventsRequested().addAll(_sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1NotificationEventsRequested);
        org.alc.ws.stub.fedex.track.EMailNotificationFormatType _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1Format = org.alc.ws.stub.fedex.track.EMailNotificationFormatType.HTML;
        _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1.setFormat(_sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1Format);
        org.alc.ws.stub.fedex.track.Localization _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1Localization = new org.alc.ws.stub.fedex.track.Localization();
        _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1Localization.setLanguageCode("LanguageCode-1396496191");
        _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1Localization.setLocaleCode("LocaleCode1376427663");
        _sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1.setLocalization(_sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1Localization);
        _sendNotifications_sendNotificationsRequestNotificationDetailRecipients.add(_sendNotifications_sendNotificationsRequestNotificationDetailRecipientsVal1);
        _sendNotifications_sendNotificationsRequestNotificationDetail.getRecipients().addAll(_sendNotifications_sendNotificationsRequestNotificationDetailRecipients);
        _sendNotifications_sendNotificationsRequest.setNotificationDetail(_sendNotifications_sendNotificationsRequestNotificationDetail);
        org.alc.ws.stub.fedex.track.SendNotificationsReply _sendNotifications__return = port.sendNotifications(_sendNotifications_sendNotificationsRequest);
        System.out.println("sendNotifications.result=" + _sendNotifications__return);


        }
        {
        System.out.println("Invoking sendSignatureProofOfDeliveryFax...");
        org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryFaxRequest _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest = new org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryFaxRequest();
        org.alc.ws.stub.fedex.track.WebAuthenticationDetail _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestWebAuthenticationDetail = new org.alc.ws.stub.fedex.track.WebAuthenticationDetail();
        org.alc.ws.stub.fedex.track.WebAuthenticationCredential _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestWebAuthenticationDetailUserCredential = new org.alc.ws.stub.fedex.track.WebAuthenticationCredential();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestWebAuthenticationDetailUserCredential.setKey("Key-1016359815");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestWebAuthenticationDetailUserCredential.setPassword("Password1230716549");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestWebAuthenticationDetail.setUserCredential(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestWebAuthenticationDetailUserCredential);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest.setWebAuthenticationDetail(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestWebAuthenticationDetail);
        org.alc.ws.stub.fedex.track.ClientDetail _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetail = new org.alc.ws.stub.fedex.track.ClientDetail();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetail.setAccountNumber("AccountNumber1005049525");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetail.setMeterNumber("MeterNumber1848184766");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetail.setIntegratorId("IntegratorId-64654127");
        org.alc.ws.stub.fedex.track.Localization _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetailLocalization.setLanguageCode("LanguageCode1745925791");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetailLocalization.setLocaleCode("LocaleCode1488952894");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetail.setLocalization(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetailLocalization);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest.setClientDetail(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestClientDetail);
        org.alc.ws.stub.fedex.track.TransactionDetail _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestTransactionDetail = new org.alc.ws.stub.fedex.track.TransactionDetail();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestTransactionDetail.setCustomerTransactionId("CustomerTransactionId852017403");
        org.alc.ws.stub.fedex.track.Localization _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestTransactionDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestTransactionDetailLocalization.setLanguageCode("LanguageCode756726029");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestTransactionDetailLocalization.setLocaleCode("LocaleCode-265143334");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestTransactionDetail.setLocalization(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestTransactionDetailLocalization);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest.setTransactionDetail(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestTransactionDetail);
        org.alc.ws.stub.fedex.track.VersionId _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestVersion = new org.alc.ws.stub.fedex.track.VersionId();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestVersion.setServiceId("ServiceId269101093");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestVersion.setMajor(-1247014128);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestVersion.setIntermediate(1556674660);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestVersion.setMinor(831317139);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest.setVersion(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestVersion);
        org.alc.ws.stub.fedex.track.QualifiedTrackingNumber _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumber = new org.alc.ws.stub.fedex.track.QualifiedTrackingNumber();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumber.setTrackingNumber("TrackingNumber1465387524");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumber.setShipDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-22T17:30:47.128+08:00"));
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumber.setAccountNumber("AccountNumber164123890");
        org.alc.ws.stub.fedex.track.CarrierCodeType _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberCarrier = org.alc.ws.stub.fedex.track.CarrierCodeType.FDXC;
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumber.setCarrier(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberCarrier);
        org.alc.ws.stub.fedex.track.Address _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination = new org.alc.ws.stub.fedex.track.Address();
        java.util.List<java.lang.String> _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestinationStreetLines = new java.util.ArrayList<java.lang.String>();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination.getStreetLines().addAll(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestinationStreetLines);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination.setCity("City207038307");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination.setStateOrProvinceCode("StateOrProvinceCode1669716743");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination.setPostalCode("PostalCode-1023036617");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination.setUrbanizationCode("UrbanizationCode490751274");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination.setCountryCode("CountryCode-708535880");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination.setCountryName("CountryName-1051897610");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination.setResidential(Boolean.valueOf(false));
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumber.setDestination(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumberDestination);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest.setQualifiedTrackingNumber(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestQualifiedTrackingNumber);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest.setAdditionalComments("AdditionalComments935028838");
        org.alc.ws.stub.fedex.track.ContactAndAddress _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSender = new org.alc.ws.stub.fedex.track.ContactAndAddress();
        org.alc.ws.stub.fedex.track.Contact _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact = new org.alc.ws.stub.fedex.track.Contact();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact.setPersonName("PersonName-419527775");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact.setTitle("Title-1453545102");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact.setCompanyName("CompanyName1446277835");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact.setPhoneNumber("PhoneNumber-2051959331");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact.setPhoneExtension("PhoneExtension1324440808");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact.setTollFreePhoneNumber("TollFreePhoneNumber-106634370");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact.setPagerNumber("PagerNumber-1748561419");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact.setFaxNumber("FaxNumber1588788929");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact.setEMailAddress("EMailAddress-1379104923");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSender.setContact(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderContact);
        org.alc.ws.stub.fedex.track.Address _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress = new org.alc.ws.stub.fedex.track.Address();
        java.util.List<java.lang.String> _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddressStreetLines = new java.util.ArrayList<java.lang.String>();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress.getStreetLines().addAll(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddressStreetLines);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress.setCity("City160664897");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress.setStateOrProvinceCode("StateOrProvinceCode-309128485");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress.setPostalCode("PostalCode-157944672");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress.setUrbanizationCode("UrbanizationCode1091754641");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress.setCountryCode("CountryCode-1359664631");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress.setCountryName("CountryName-1007350855");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress.setResidential(Boolean.valueOf(false));
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSender.setAddress(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSenderAddress);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest.setFaxSender(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxSender);
        org.alc.ws.stub.fedex.track.ContactAndAddress _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipient = new org.alc.ws.stub.fedex.track.ContactAndAddress();
        org.alc.ws.stub.fedex.track.Contact _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact = new org.alc.ws.stub.fedex.track.Contact();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact.setPersonName("PersonName-1645226919");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact.setTitle("Title-108432237");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact.setCompanyName("CompanyName-286364315");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact.setPhoneNumber("PhoneNumber2002142068");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact.setPhoneExtension("PhoneExtension-1636924620");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact.setTollFreePhoneNumber("TollFreePhoneNumber-1406991991");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact.setPagerNumber("PagerNumber-229618307");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact.setFaxNumber("FaxNumber-2139410077");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact.setEMailAddress("EMailAddress174882167");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipient.setContact(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientContact);
        org.alc.ws.stub.fedex.track.Address _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress = new org.alc.ws.stub.fedex.track.Address();
        java.util.List<java.lang.String> _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddressStreetLines = new java.util.ArrayList<java.lang.String>();
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress.getStreetLines().addAll(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddressStreetLines);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress.setCity("City1337984587");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress.setStateOrProvinceCode("StateOrProvinceCode-1702092833");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress.setPostalCode("PostalCode1532024004");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress.setUrbanizationCode("UrbanizationCode-2014021145");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress.setCountryCode("CountryCode-274577422");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress.setCountryName("CountryName1666323294");
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress.setResidential(Boolean.valueOf(true));
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipient.setAddress(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipientAddress);
        _sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest.setFaxRecipient(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequestFaxRecipient);
        org.alc.ws.stub.fedex.track.SignatureProofOfDeliveryFaxReply _sendSignatureProofOfDeliveryFax__return = port.sendSignatureProofOfDeliveryFax(_sendSignatureProofOfDeliveryFax_signatureProofOfDeliveryFaxRequest);
        System.out.println("sendSignatureProofOfDeliveryFax.result=" + _sendSignatureProofOfDeliveryFax__return);


        }
        {
        System.out.println("Invoking track...");
        org.alc.ws.stub.fedex.track.TrackRequest _track_trackRequest = new org.alc.ws.stub.fedex.track.TrackRequest();
        org.alc.ws.stub.fedex.track.WebAuthenticationDetail _track_trackRequestWebAuthenticationDetail = new org.alc.ws.stub.fedex.track.WebAuthenticationDetail();
        org.alc.ws.stub.fedex.track.WebAuthenticationCredential _track_trackRequestWebAuthenticationDetailUserCredential = new org.alc.ws.stub.fedex.track.WebAuthenticationCredential();
        _track_trackRequestWebAuthenticationDetailUserCredential.setKey("Key894524815");
        _track_trackRequestWebAuthenticationDetailUserCredential.setPassword("Password1766356625");
        _track_trackRequestWebAuthenticationDetail.setUserCredential(_track_trackRequestWebAuthenticationDetailUserCredential);
        _track_trackRequest.setWebAuthenticationDetail(_track_trackRequestWebAuthenticationDetail);
        org.alc.ws.stub.fedex.track.ClientDetail _track_trackRequestClientDetail = new org.alc.ws.stub.fedex.track.ClientDetail();
        _track_trackRequestClientDetail.setAccountNumber("AccountNumber-1486092879");
        _track_trackRequestClientDetail.setMeterNumber("MeterNumber-1949723686");
        _track_trackRequestClientDetail.setIntegratorId("IntegratorId-488385836");
        org.alc.ws.stub.fedex.track.Localization _track_trackRequestClientDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
        _track_trackRequestClientDetailLocalization.setLanguageCode("LanguageCode-1869907779");
        _track_trackRequestClientDetailLocalization.setLocaleCode("LocaleCode1757364910");
        _track_trackRequestClientDetail.setLocalization(_track_trackRequestClientDetailLocalization);
        _track_trackRequest.setClientDetail(_track_trackRequestClientDetail);
        org.alc.ws.stub.fedex.track.TransactionDetail _track_trackRequestTransactionDetail = new org.alc.ws.stub.fedex.track.TransactionDetail();
        _track_trackRequestTransactionDetail.setCustomerTransactionId("CustomerTransactionId908530329");
        org.alc.ws.stub.fedex.track.Localization _track_trackRequestTransactionDetailLocalization = new org.alc.ws.stub.fedex.track.Localization();
        _track_trackRequestTransactionDetailLocalization.setLanguageCode("LanguageCode1892793798");
        _track_trackRequestTransactionDetailLocalization.setLocaleCode("LocaleCode-884577457");
        _track_trackRequestTransactionDetail.setLocalization(_track_trackRequestTransactionDetailLocalization);
        _track_trackRequest.setTransactionDetail(_track_trackRequestTransactionDetail);
        org.alc.ws.stub.fedex.track.VersionId _track_trackRequestVersion = new org.alc.ws.stub.fedex.track.VersionId();
        _track_trackRequestVersion.setServiceId("ServiceId1196327608");
        _track_trackRequestVersion.setMajor(-1819886233);
        _track_trackRequestVersion.setIntermediate(776479160);
        _track_trackRequestVersion.setMinor(-786933401);
        _track_trackRequest.setVersion(_track_trackRequestVersion);
        java.util.List<org.alc.ws.stub.fedex.track.TrackSelectionDetail> _track_trackRequestSelectionDetails = new java.util.ArrayList<org.alc.ws.stub.fedex.track.TrackSelectionDetail>();
        org.alc.ws.stub.fedex.track.TrackSelectionDetail _track_trackRequestSelectionDetailsVal1 = new org.alc.ws.stub.fedex.track.TrackSelectionDetail();
        org.alc.ws.stub.fedex.track.CarrierCodeType _track_trackRequestSelectionDetailsVal1CarrierCode = org.alc.ws.stub.fedex.track.CarrierCodeType.FDXE;
        _track_trackRequestSelectionDetailsVal1.setCarrierCode(_track_trackRequestSelectionDetailsVal1CarrierCode);
        org.alc.ws.stub.fedex.track.OperatingCompanyType _track_trackRequestSelectionDetailsVal1OperatingCompany = org.alc.ws.stub.fedex.track.OperatingCompanyType.FEDEX_CUSTOMER_INFORMATION_SYSTEMS;
        _track_trackRequestSelectionDetailsVal1.setOperatingCompany(_track_trackRequestSelectionDetailsVal1OperatingCompany);
        org.alc.ws.stub.fedex.track.TrackPackageIdentifier _track_trackRequestSelectionDetailsVal1PackageIdentifier = new org.alc.ws.stub.fedex.track.TrackPackageIdentifier();
        org.alc.ws.stub.fedex.track.TrackIdentifierType _track_trackRequestSelectionDetailsVal1PackageIdentifierType = org.alc.ws.stub.fedex.track.TrackIdentifierType.RETURN_MATERIALS_AUTHORIZATION;
        _track_trackRequestSelectionDetailsVal1PackageIdentifier.setType(_track_trackRequestSelectionDetailsVal1PackageIdentifierType);
        _track_trackRequestSelectionDetailsVal1PackageIdentifier.setValue("Value-952438604");
        _track_trackRequestSelectionDetailsVal1.setPackageIdentifier(_track_trackRequestSelectionDetailsVal1PackageIdentifier);
        _track_trackRequestSelectionDetailsVal1.setTrackingNumberUniqueIdentifier("TrackingNumberUniqueIdentifier-666264123");
        _track_trackRequestSelectionDetailsVal1.setShipDateRangeBegin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-22T17:30:47.131+08:00"));
        _track_trackRequestSelectionDetailsVal1.setShipDateRangeEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-22T17:30:47.131+08:00"));
        _track_trackRequestSelectionDetailsVal1.setShipmentAccountNumber("ShipmentAccountNumber-1625544705");
        _track_trackRequestSelectionDetailsVal1.setSecureSpodAccount("SecureSpodAccount472537189");
        org.alc.ws.stub.fedex.track.Address _track_trackRequestSelectionDetailsVal1Destination = new org.alc.ws.stub.fedex.track.Address();
        java.util.List<java.lang.String> _track_trackRequestSelectionDetailsVal1DestinationStreetLines = new java.util.ArrayList<java.lang.String>();
        _track_trackRequestSelectionDetailsVal1Destination.getStreetLines().addAll(_track_trackRequestSelectionDetailsVal1DestinationStreetLines);
        _track_trackRequestSelectionDetailsVal1Destination.setCity("City1582937587");
        _track_trackRequestSelectionDetailsVal1Destination.setStateOrProvinceCode("StateOrProvinceCode-2072494097");
        _track_trackRequestSelectionDetailsVal1Destination.setPostalCode("PostalCode-118046363");
        _track_trackRequestSelectionDetailsVal1Destination.setUrbanizationCode("UrbanizationCode-1877974593");
        _track_trackRequestSelectionDetailsVal1Destination.setCountryCode("CountryCode218725813");
        _track_trackRequestSelectionDetailsVal1Destination.setCountryName("CountryName-1191777508");
        _track_trackRequestSelectionDetailsVal1Destination.setResidential(Boolean.valueOf(false));
        _track_trackRequestSelectionDetailsVal1.setDestination(_track_trackRequestSelectionDetailsVal1Destination);
        org.alc.ws.stub.fedex.track.PagingDetail _track_trackRequestSelectionDetailsVal1PagingDetail = new org.alc.ws.stub.fedex.track.PagingDetail();
        _track_trackRequestSelectionDetailsVal1PagingDetail.setPagingToken("PagingToken1401877824");
        _track_trackRequestSelectionDetailsVal1PagingDetail.setNumberOfResultsPerPage(new java.math.BigInteger("26819434838303203928487022786443123181"));
        _track_trackRequestSelectionDetailsVal1.setPagingDetail(_track_trackRequestSelectionDetailsVal1PagingDetail);
        _track_trackRequestSelectionDetailsVal1.setCustomerSpecifiedTimeOutValueInMilliseconds(new java.math.BigInteger("-4474035380856535306915804977921597"));
        _track_trackRequestSelectionDetails.add(_track_trackRequestSelectionDetailsVal1);
        _track_trackRequest.getSelectionDetails().addAll(_track_trackRequestSelectionDetails);
        _track_trackRequest.setTransactionTimeOutValueInMilliseconds(new java.math.BigInteger("61299777294735746289143467268759992335"));
        java.util.List<org.alc.ws.stub.fedex.track.TrackRequestProcessingOptionType> _track_trackRequestProcessingOptions = new java.util.ArrayList<org.alc.ws.stub.fedex.track.TrackRequestProcessingOptionType>();
        org.alc.ws.stub.fedex.track.TrackRequestProcessingOptionType _track_trackRequestProcessingOptionsVal1 = org.alc.ws.stub.fedex.track.TrackRequestProcessingOptionType.INCLUDE_DETAILED_SCANS;
        _track_trackRequestProcessingOptions.add(_track_trackRequestProcessingOptionsVal1);
        _track_trackRequest.getProcessingOptions().addAll(_track_trackRequestProcessingOptions);
        org.alc.ws.stub.fedex.track.TrackReply _track__return = port.track(_track_trackRequest);
        System.out.println("track.result=" + _track__return);


        }

        System.exit(0);
    }

}
